
openvpn_srv01_mask: 255.255.255.0

yum_install_all:
      - mc
      - iptables-services
      - kbd
      - epel-release
      - tcpdump
      - nano
      - setools-console
      - setroubleshoot-server
      - openvpn
      - easy-rsa
      - iperf3.x86_64
      - NetworkManager-libnm
      - nm-connection-editor

openvpn_tunel_client_net:
          ip_tunel_client_net_start: 10.10.10.3
          ip_tunel_client_net_stop: 10.10.10.20
